name: cullr
description: A new Flutter project.
publish_to: none
version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  photo_manager: ^3.8.3
  video_player: ^2.10.1
  flutter_card_swiper: ^7.2.0
  flutter_svg: ^2.0.14
  permission_handler: ^12.0.1
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/bmc_button.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true
